---
- hosts: all
  remote_user: "{{ user }}"
  tasks:

  - name: upgrade & update cache (Ubuntu)
    tags: update,ubuntu
    apt:
      upgrade: dist
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

  - name: install package updates and upgrade (AMI)
    tags: update,upgrade,ami
    yum:
      name: "*"
      state: latest
      update_cache: yes
      exclude: kernel*
    changed_when: false
    when: ansible_distribution == "Amazon"

  - name: create user, cloudlord
    tags: always
    user:
      name: cloudlord
      groups: "{{ sudo_group }}"

  - name: add ssh_key for cloudlord
    tags: always
    authorized_key:
      user: cloudlord
      key: "{{lookup('ansible.builtin.file', '~/.ssh/id_ed25519.pub') }}"

  - name: copy authentication key.pem file to new user, cloudlord
    tags: always
    copy:
      src: ~/newkey.pem
      dest: /home/cloudlord/newkey.pem
      mode: 0444
      owner: cloudlord
      group: cloudlord

  - name: copy authentication key.pem file to root
    tags: always
    copy:
      src: ~/newkey.pem
      dest: /root/newkey.pem
      mode: 0444
      owner: root
      group: root

  - name: add cloudlord to sudoers
    tags: always
    copy:
      src: sudoer_cloudlord
      dest: /etc/sudoers.d/cloudlord
      owner: root
      group: root
      mode: 0440